### ISSUE TITLE
首页

### ISSUE THREAD

**Issue by FrogDar** [FrogDar/HinghwaDict-frontend#29]
![image](https://user-images.githubusercontent.com/20886330/157160864-c3effdef-b1bb-46ef-aac7-638e555c414f.png)

- 未登录时没办法用搜索框
- 轮播图里是不是有bug，多了一篇”学堂生vs八股生“的文章？

**Comment by FrogDar** [comment]
未登录的时候点击那个人头显示请先登录之后
能不能马上触发登录操作，相当于点击了一下登录？

**Comment by MsunM-cell** [comment]
> ![image](https://user-images.githubusercontent.com/20886330/157160864-c3effdef-b1bb-46ef-aac7-638e555c414f.png)
> 
> * 未登录时没办法用搜索框
> * 轮播图里是不是有bug，多了一篇”学堂生vs八股生“的文章？

调用website/announcements借口，返回3篇文章，包括“学堂生vs八股生”。

**Comment by FrogDar** [comment]
我晓得了）
应该是调错接口了
其实轮播图理论上是`GET /website/carousel`
有学堂生的是本站公告 `GET /website/announcements`
