### ISSUE TITLE
录音提交页面的loading

### ISSUE THREAD

**Issue by FrogDar** [FrogDar/HinghwaDict-frontend#33]
由于没有提交中的提示信息，用户可能误以为没有成功点击提交，导致多次点击发布按钮
![1f9e86f2a8ddf5e216c4065095dd1e1](https://user-images.githubusercontent.com/20886330/160266281-1a0227a0-3b07-4730-b77d-b8728be536d6.png)

在当前会导致录音重复提交多次

**Comment by MsunM-cell** [comment]
Completed.
