### ISSUE TITLE
授权登录没有真正登录

### ISSUE THREAD

**Issue by FrogDar** [FrogDar/HinghwaDict-frontend#34]
当我点击了一键登录之后
![image](https://user-images.githubusercontent.com/20886330/162583287-2e4d5ca9-e9e7-49d9-adea-0d282469e859.png)
说是登录成功，但是实际上并没有成功登录
![image](https://user-images.githubusercontent.com/20886330/162583308-4cb5ba47-281c-44d8-9ac2-878146b8be89.png)

可能是登录逻辑没有判断好？

**Comment by FrogDar** [comment]
对了 那个 `请先授权登录` 改成 `请先登录` 吧） 不一定非得授权了才能登录）

**Comment by MsunM-cell** [comment]
> 当我点击了一键登录之后 ![image](https://user-images.githubusercontent.com/20886330/162583287-2e4d5ca9-e9e7-49d9-adea-0d282469e859.png) 说是登录成功，但是实际上并没有成功登录 ![image](https://user-images.githubusercontent.com/20886330/162583308-4cb5ba47-281c-44d8-9ac2-878146b8be89.png)
> 
> 可能是登录逻辑没有判断好？

诶 我这边貌似没有问题 好奇怪

**Comment by MsunM-cell** [comment]
> 对了 那个 `请先授权登录` 改成 `请先登录` 吧） 不一定非得授权了才能登录）

嗯嗯 这个改了

**Comment by FrogDar** [comment]
> > 当我点击了一键登录之后 ![image](https://user-images.githubusercontent.com/20886330/162583287-2e4d5ca9-e9e7-49d9-adea-0d282469e859.png) 说是登录成功，但是实际上并没有成功登录 ![image](https://user-images.githubusercontent.com/20886330/162583308-4cb5ba47-281c-44d8-9ac2-878146b8be89.png)
> > 可能是登录逻辑没有判断好？
> 
> 诶 我这边貌似没有问题 好奇怪

怪事 难道是电脑版微信的bug？我在手机上实验也好好的
