### ISSUE TITLE
条件查字功能升级

### ISSUE THREAD

**Issue by FrogDar** [FrogDar/HinghwaDict-frontend#36]
条件查字其实已经有了新接口 `CH0204` 支持了 繁体字、对应词条、语音等多种功能，web端的功能已经上新，小程序端也可以考虑合理布局，实现相关功能

https://pxm.edialect.top/tools/conditions
![image](https://user-images.githubusercontent.com/20886330/162583600-2727ddb7-f93d-4de2-95b3-c68ce2e9e89f.png)

**Comment by MsunM-cell** [comment]
差不多了
